SELECT * FROM 
(SELECT CITY C, LENGTH(CITY) L 
FROM STATION ORDER BY L DESC, C ASC) 
WHERE ROWNUM=1;

SELECT * FROM 
(SELECT CITY C, LENGTH(CITY) L 
FROM STATION ORDER BY L ASC, C ASC) 
WHERE ROWNUM=1;